import rhinoscriptsyntax as rs
#in progress do not use.



def offsetCurveOnSurface():
    curve = rs.GetObject("sel curve",4)
    num = 100
    points = rs.DivideCurve(curve,num)
    surface = rs.GetObject("sel surface", 8)
    offset_dist = 150
    offset_points = []
    
    for point in points:
        parameter =  rs.SurfaceClosestPoint(surface,point)
        crv = rs.ExtractIsoCurve(surface,parameter, 2)
        #create sphere at end
        startPt = rs.CurveStartPoint(crv)
        endPt = rs.CurveEndPoint(crv)
        startSphere = rs.AddSphere(startPt,offset_dist)
        endSphere = rs.AddSphere(endPt,offset_dist)
        #intersect sphere with end
        tupStart = rs.CurveSurfaceIntersection(crv,startSphere)
        tupEnd = rs.CurveSurfaceIntersection(crv,endSphere)
        
        
        #offset_points.append(offset_point)
        
offsetCurveOnSurface()
